version: 2.1

executors:
  node:
    docker:
      - image: circleci/node:latest
  working_directory: '~/sasstastical-free'

commands:
  install_packages:
    description: 'Install Packages'
    steps:
      - restore_cache:
          keys:
            - 'v2-yarn-{{ checksum "yarn.lock" }}'
      - run: npm install -g yarn
      - run: yarn
      - save_cache:
          key: v2-yarn-{{ checksum "yarn.lock" }}
          when: on_success
          paths:
            - ~/thecodechef.github.io/node_modules
  run_gulp:
    description: 'Run Gulp'
    steps:
      - run: gulp
jobs:
  install:
    executor: node
    steps:
      - checkout
      - install_packages
  build:
    executor: node
    steps:
      - run_gulp

workflows:
  version: 2
  build_with_gulp:
    jobs:
      - install
      - build:
          requires:
            - install
          filters:
            branches:
              only: master
